
name: Hilmy Baja
title: Hilmy Baja
description: "Hilmy's personal website."
url: "https://hilmybaja.com"
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

collections:
  news:
    output: false
  videogames:
    output: true
    permalink: /videogames/:title/

theme_options:
  google_analytics: G-241HN9TB7S

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
