
name: Nithin Bekal
title: Nithin Bekal
description: "Nithin Bekal's blog about programming - Ruby, Rails, Vim, Elixir."
url: https://nithinbekal.com
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

theme_options:
  disqus_shortname: nithinbekal
  google_analytics: G-241HN9TB7S

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
